#!/data/data/com.termux/files/usr/bin/sh
p='\033[1;33m'
g='\033[1;32m'
s='\033[1;34m'

echo " "
echo " "
sleep 2
echo "$s *********************************** $s"
echo " "
echo " "
echo "$g Bash.bashrc setup ho rha hai $g"
echo "$g wait some time $g"
echo " "
echo " "
echo "$s ********************************** $s"
cd ..
cd storage/dcim
cp bash.bashrc /data/data/com.termux/files/usr/etc
cd $HOME
cd ..
cd usr
cd etc
chmod 700 bash.bashrc
sleep 10
echo " "
echo " "
echo "$s *********************************** $s"
echo " "
echo " "
echo "$p Successfully setup ho gya $p"
echo " "
echo " "
echo "$p Ab new session kar ke dekh sakte ho $p"
echo " "
echo " "
echo "$s *********************************** $s"
